platform :ios, "7.1"

pod "SVProgressHUD"
pod 'SimulatorStatusMagic', :configurations => ['Debug']

target 'PublishingTestApp' do
end

target 'New Target' do
end

target 'New Target' do
end

target 'Ha Ha' do
end

target 'Ha Ha' do
end